### ISSUE TITLE
seg-fault in utimens on linux-64

### ISSUE THREAD

**Issue by cboddy** [SerCeMan/jnr-fuse#11]
Firstly, many thanks for this very useful project!

However, when overriding utimens in FuseStubFS to set the last-modified time we see the seg-fault below when trying to access the tv_sec attribute of the modified time in the snippet below. 

<pre>
@Override
    public int utimens(String s, Timespec[] timespecs) {
        Timespec access = timespecs[0], modified = timespecs[1];
        long epochSeconds = modified.tv_sec.get();
}
</pre>

Is this expected?

[junit] # An error report file with more information is saved as:
    [junit] # /home/chrirs/software/Peergos/hs_err_pid13102.log
    [junit] Compiled method (nm)   22930  150     n 0       sun.misc.Unsafe::getLong (native)
    [junit]  total in heap  [0x00007fa63915eb50,0x00007fa63915ee98] = 840
    [junit]  relocation     [0x00007fa63915ec78,0x00007fa63915ecc0] = 72
    [junit]  main code      [0x00007fa63915ecc0,0x00007fa63915ee98] = 472
    [junit] Compiled method (nm)   22930  150     n 0       sun.misc.Unsafe::getLong (native)
    [junit]  total in heap  [0x00007fa63915eb50,0x00007fa63915ee98] = 840
    [junit]  relocation     [0x00007fa63915ec78,0x00007fa63915ecc0] = 72
    [junit]  main code      [0x00007fa63915ecc0,0x00007fa63915ee98] = 472
    [junit]    create[0] flags: 0x80c2 /test02/34da12df-7638-4a8a-aa32-772994a18dd5
    [junit] fgetattr[0] /test02/34da12df-7638-4a8a-aa32-772994a18dd5
    [junit]    NODEID: 35
    [junit]    unique: 389, success, outsize: 160
    [junit] unique: 390, opcode: FLUSH (25), nodeid: 35, insize: 64, pid: 13104
    [junit] flush[0]
    [junit] lock[0] F_SETLK F_UNLCK start: 0 len: 0 pid: 0
    [junit]    unique: 390, success, outsize: 16
    [junit] unique: 391, opcode: RELEASE (18), nodeid: 35, insize: 64, pid: 0
    [junit]    unique: 391, success, outsize: 16
    [junit] unique: 392, opcode: OPEN (14), nodeid: 35, insize: 48, pid: 13104
    [junit] open flags: 0x8000 /test02/34da12df-7638-4a8a-aa32-772994a18dd5
    [junit]    open[0] flags: 0x8000 /test02/34da12df-7638-4a8a-aa32-772994a18dd5
    [junit]    unique: 392, success, outsize: 32
    [junit] unique: 393, opcode: SETATTR (4), nodeid: 35, insize: 128, pid: 13104
    [junit] utimens /test02/34da12df-7638-4a8a-aa32-772994a18dd5 0.000000000 1461698071.609000000

**Comment by SerCeMan** [comment]
Hi, @cboddy 

First of all I should ask you, do you use latest version? Because I've already fixed similar problem recently.

**Comment by SerCeMan** [comment]
Hi, @cboddy. 

Is this problem still actual?

**Comment by cboddy** [comment]
Hi @SerCeMan,

Apologies for the slow response; updating from jnr-fuse version 0.2.1 to 0.3 appears to fix the issue; I'll close the ticket.

Thanks!
