### ISSUE TITLE
Wrong dependency scopes in release 0.5.6

### ISSUE THREAD

**Issue by overheadhunter** [SerCeMan/jnr-fuse#139]
The generated `pom.xml` contains wrong dependency scopes in version 0.5.6:

* In [version 0.5.5](https://repo.maven.apache.org/maven2/com/github/serceman/jnr-fuse/0.5.5/jnr-fuse-0.5.5.pom), the pom.xml declares dependencies with `compile` scope
* In [version 0.5.6](https://repo.maven.apache.org/maven2/com/github/serceman/jnr-fuse/0.5.6/jnr-fuse-0.5.6.pom), the pom.xml incorrectly declares dependencies with `runtime` scope

This causes compilation errors when attempting to build downstream projects, unless re-declaring all dependencies (which defies the purpose of build tools).

**Comment by overheadhunter** [comment]
Can we please have a further release, so we can upgrade from 0.5.5? That would be awesome! 🙂

**Comment by SerCeMan** [comment]
Hey, @overheadhunter! I just published 0.5.7 on central 👍
