### ISSUE TITLE
Winfsp and jnr-fuse not working

### ISSUE THREAD

**Issue by pingus69** [SerCeMan/jnr-fuse#155]
Hi,

first thanks a lot for the jnr-fuse. It is working great on macOS and Linux since years.
Now I want o run my project also under Windows (10).
I testet it on Window 10 VM machine in Azure cloud and Windows Server 16 on an VMWare guest in my office.
 I am using Winfsp 2022 from secfs.net and jnr-fuse  0.5.7)
But unfortunately  I can't get the examples (HelloWorld,Memfs)  to work.

When I run the HelloWorld example and mount the filesystem on M:\

I don't see the mounted M: and I cannot access.

But when I run

fsptool lsvol 

I get

M:  \Device\Volume{704a1994-8110-11ec-86f6-000d3aaed942}

But when I mount to an existing drive with a non-existing directory (e.g. C:\tmp\mnth I get the following behaviour:
<div>
cd C:\tmp

C:\tmp>dir

 Directory of C:\tmp

01/30/2022  08:42 AM    \<DIR\>          .
01/30/2022  08:42 AM    \<DIR\>          ..
01/30/2022  08:42 AM    \<DIR\>          mnth
               0 File(s)              0 bytes
               3 Dir(s)  16,920,776,704 bytes free

C:\tmp>cd mnth
The system cannot find the file specified.

C:\tmp>dir
 Volume in drive C is Windows
 Volume Serial Number is B058-8F2A

 Directory of C:\tmp

01/30/2022  08:42 AM    \<DIR\>          .
01/30/2022  08:42 AM    \<DIR\>          ..
01/30/2022  08:42 AM    \<JUNCTION\>     mnth [\Device\Volume{704a1a06-8110-11ec-86f6-000d3aaed942}\]
               0 File(s)              0 bytes
               3 Dir(s)  16,920,772,608 bytes free
</div>

Here the output of the running HelloWorld:

java[TID=29cc]: FFFF808A9FD58270: >>QueryVolumeInformation
java[TID=29cc]: FFFF808A9FD58270: <<QueryVolumeInformation IoStatus=0[0] VolumeInfo={TotalSize=0:0, FreeSize=0:0, VolumeLabel=""}
java[TID=29cc]: FFFF808A982F3DE0: >>Create [UTB--C] "\", FILE_OPEN, CreateOptions=4001, FileAttributes=10, Security=NULL, AllocationSize=0:0, AccessToken=0000000000000578[PID=112c], DesiredAccess=0, GrantedAccess=80, ShareAccess=1
java[TID=29cc]: FFFF808A982F3DE0: <<Create IoStatus=c0000034[0]
java[TID=29cc]: FFFF808AA03ACDD0: >>Create [UT---C] "\", FILE_OPEN, CreateOptions=21, FileAttributes=10, Security=NULL, AllocationSize=0:0, AccessToken=0000000000000578[PID=2d60], DesiredAccess=100020, GrantedAccess=0, ShareAccess=3
java[TID=29cc]: FFFF808AA03ACDD0: <<Create IoStatus=c0000034[0]
<=========----> 75% EXECUTING [51s]

Any idea what is wrong here?

Thanks a lot

Bernward

**Comment by SerCeMan** [comment]
Hey, @pingus69! Have you tried to check out the [#troubleshooting](https://github.com/SerCeMan/jnr-fuse/blob/master/INSTALLATION.md) section and specify the encoding explicitly?

**Comment by pingus69** [comment]
Hi Sergey, yes this solves my problem! Thank you very much!!


Bernward

**Comment by Erhannis** [comment]
Comment: that's a runtime flag, not a compiler flag.  (Do `java -Dfile.encoding=UTF-8 ...`, not `gradle -Dfile.encoding=UTF-8 ...`)  I speak from experience.
