### ISSUE TITLE
The wrapper.jar is stale.

### ISSUE THREAD

**Issue by HappyHacker123** [SerCeMan/jnr-fuse#181]
# Problem Description
Currently jnr-fuse is using gradle 7.2 as mentioned in gradle-wrapper.properties and the checksum of current wrapper.jar is e996d452d2645e70c01c11143ca2d3742734a28da2bf61f25c82bdc288c9e637. However, as can be seen from official doc https://gradle.org/release-checksums/, the expected checksum of wrapper.jar 7.2 should be 33ad4583fd7ee156f533778736fa1b4940bd83b433934d1cc4e9f608e99a6a89. The inconsistency means that the wrapper.jar is stale and should be updated.

# Possible Solution 
As mentioned in gradle official document https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:upgrading_wrapper, you will need to run the wrapper task a second time to make sure the wrapper.jar is updated. You can run the below command in the root project. Automatically the wrapper scripts will be generated by gradle with corresponding version.
```
bash gradlew wrapper
```

**Comment by SerCeMan** [comment]
Hey, @HappyHacker123! Thanks, I'll take a look at bumping the jar later this week. For my understanding, could you describe the impact of the mismatch?

**Comment by HappyHacker123** [comment]
Thanks for your reply :) @SerCeMan . Like with any software the jar gets bug fixes or new features when upgraded.  So it's better to keep the jar consistent with gradle version. It's recommended by gradle's official doc to update the wrapper scripts when upgrading gradle version
> Don’t forget to run the wrapper task again to download the Gradle distribution binaries (if needed) and update the gradlew and gradle.bat files.

If I recall correctly, one example is that with older versions of jar and scripts, the CLI process will use more RAM than newer versions.

**Comment by SerCeMan** [comment]
Thank you for reporting, fixed in https://github.com/SerCeMan/jnr-fuse/pull/182
