### ISSUE TITLE
Can't run in gradle

### ISSUE THREAD

**Issue by Heachy** [SerCeMan/jnr-fuse#183]
### Run the [MemoryFS ](https://github.com/SerCeMan/jnr-fuse/blob/master/src/main/java/ru/serce/jnrfuse/examples/MemoryFS.java) sample
![image](https://github.com/SerCeMan/jnr-fuse/assets/90972647/cd2236ac-3716-4a86-8b0c-e4cb79972df3)
![image](https://github.com/SerCeMan/jnr-fuse/assets/90972647/abb0d60b-1b73-4e2a-8ec9-392529e216ef)
![image](https://github.com/SerCeMan/jnr-fuse/assets/90972647/08dbbf58-4159-48b1-85ab-3cae19f7def6)
**Unable to access the mounted J drive**

**But when I use maven to build the project, MemoryFS runs normally.**
![image](https://github.com/SerCeMan/jnr-fuse/assets/90972647/45da87e8-8df0-4efd-83d3-53bac50bd66e)

**Is it because I haven’t configured it somewhere? I am using a Windows system. Hope to get help.QAQ**

**Comment by SerCeMan** [comment]
Hey, @Heachy! Could you attach the logs? They might help reveal the issue. Also, since you're running on Windows, please check that UTF-8 is used, [INSTALLATION.md#troubleshooting](https://github.com/SerCeMan/jnr-fuse/blob/master/INSTALLATION.md#troubleshooting).

**Comment by Heachy** [comment]
Here it shows that the service has been started
![image](https://github.com/SerCeMan/jnr-fuse/assets/90972647/7ce9e9d1-e7d8-43ea-8c73-7c5ff5e57323)

I don't understand the following debug log very well. It should be triggered when the file directory is opened.
![image](https://github.com/SerCeMan/jnr-fuse/assets/90972647/bddf1fcc-fdf9-4c86-80f4-b6415ee162f2)

Is this the correct way to configure UTF-8?
![image](https://github.com/SerCeMan/jnr-fuse/assets/90972647/63d17070-ccde-4c1c-9ce1-29217a984d4d)

But for the project built by maven, I just import the jnr-fuse dependency, then copy the MemoryFS sample code and run it directly. The corresponding files can also be opened in Windows systems. I'm still quite curious about this.
