### ISSUE TITLE
Request for a new release to include ARM (AArch64) support

### ISSUE THREAD

**Issue by jasondrogba** [SerCeMan/jnr-fuse#188]
Hi @SerCeMan,
I noticed that the PR [Add AArch64 (64-bit ARM) Linux support](https://github.com/SerCeMan/jnr-fuse/pull/172) has been successfully merged into the main branch. This is a great improvement for those of us working on ARM-based systems.

However, the latest release (v0.5.7) doesn't yet include this support. Would it be possible to publish a new release, such as v0.5.8, that include this ARM (AArch64) support? This would be very helpful for users working with ARM architectures.

Thank you for your hard work on this project!

**Comment by SerCeMan** [comment]
Hey, @jasondrogba! The new version – `0.5.8`. Please let me know how it goes!

**Comment by jasondrogba** [comment]
Thank you very much! I will upgrade the jnr-fuse version used by Alluxio FUSE to 0.5.8 and then test if Alluxio FUSE works properly on AWS ARM machines with the following checks:
- Basic Linux operations such as mkdir, touch, cd, ls, etc.
- Fio testing, comparing the results with those from x86 machines.
- Ideally, we should comprehensively cover all FUSE functions for verification.

**Comment by SerCeMan** [comment]
Hey, @jasondrogba! I believe it's already on maven central, e.g. you can see it here: https://search.maven.org/artifact/com.github.serceman/jnr-fuse/0.5.8/jar. 

https://mvnrepository.com is just a search engine, and it's not always up-to-date, e.g. you can read more about the distinction here: https://stackoverflow.com/a/62882748.
