### ISSUE TITLE
readdir is not called

### ISSUE THREAD

**Issue by czeidler** [SerCeMan/jnr-fuse#19]
I'm trying to get jnr-fuse (0.4.0) running on Ubuntu but have some trouble getting it working. I'm using the HelloFuse fs at the moment but the method readdir never gets called. The methods getattr, opendir, releasedir are working fine though. From the output I can see that fuse starts a READDIR request but it never gets through to the java code. Any idea why readdir is not working?

**Comment by SerCeMan** [comment]
Hi, @czeidler!

Is it Ubuntu x64 or x32? Did you make any change to HelloFuse?

**Comment by SerCeMan** [comment]
Can you also post the `debug` output here?

**Comment by czeidler** [comment]
Its ubuntu 17.04 x64. I started with my own implementation using only getattr and readdir but then copied HelloFuse over. So 98% sure that it unmodified. Here is some output. (Or is there some other debug output?) thanks!

```
LOOKUP /autorun.inf
getattr /autorun.inf
   unique: 8, error: -2 (No such file or directory), outsize: 16
unique: 9, opcode: READDIR (28), nodeid: 1, insize: 80, pid: 9351
readdir[0] from 0
   unique: 9, success, outsize: 16
unique: 10, opcode: RELEASEDIR (29), nodeid: 1, insize: 64, pid: 0
   unique: 10, success, outsize: 16
unique: 11, opcode: OPENDIR (27), nodeid: 1, insize: 48, pid: 9351
   unique: 11, success, outsize: 32
unique: 12, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 9351
getattr /
   unique: 12, success, outsize: 120
unique: 13, opcode: READDIR (28), nodeid: 1, insize: 80, pid: 9351
readdir[0] from 0
   unique: 13, success, outsize: 16
unique: 14, opcode: RELEASEDIR (29), nodeid: 1, insize: 64, pid: 0
   unique: 14, success, outsize: 16
```

**Comment by SerCeMan** [comment]
> I started with my own implementation using only getattr and readdir but then copied HelloFuse over

So, is it just a `HelloFuse.java` without modifications? If so, is it working correctly when you try to invoke let's say `ls`?

**Comment by czeidler** [comment]
I put breakpoints in all methods of HelloFuse but only getattr gets called. A ls only triggers a getattr but not a readdir... Maybe something with the bindings/ method signature is different under Ubuntu?

**Comment by SerCeMan** [comment]
But is it working for you? Is it showing a file called `hello`?

**Comment by czeidler** [comment]
no its showing nothing (because readdir is never called), I also tested it in the test case:
`String[]` content = tmpDir.toFile().list();
Nothing in content...

**Comment by czeidler** [comment]
Initially I used javafs (but it does not seems to be under active development any more and I had some other issues) I got my fs working for javafs, so I just checked the callback signature in javafs:
` int _readdir(String path, Pointer buf, Pointer fillFunction, @off_t long offset, @In Pointer info); `

compared to your implementation there is an additional @In, is that important?
`int readdir(String path, Pointer buf, Pointer filter, @off_t long offset, Pointer fi);`

**Comment by SerCeMan** [comment]
No, it isn't `@in` and `@out` are mostly for optimization purposes. 

Can you try to run `ru.serce.jnrfuse.struct.HelloFuseTest`?

**Comment by czeidler** [comment]
Ok found the issues. The problem was simply that I still had the javafs code around and I guess this interfered with jnr-fuse... sorry for the noise.

Just an idea: Sometimes it happens that filesystems don't get umounted (e.g. when killing the jvm) Does it makes sense to add a method to force an umount?

```
static public void umount(Path mountPoint) {
        try {
            String mountPath = mountPoint.toAbsolutePath().toString();
            try {
                new ProcessBuilder("fusermount", "-u", "-z", mountPath).start();
            } catch (IOException e) {
                new ProcessBuilder("umount", mountPath).start();
            }
        } catch (IOException e) {
            throw new FuseException("Unable to umount FS", e);
        }
    }
```

**Comment by SerCeMan** [comment]
@czeidler Yes, it might be a good idea to have `unmount` method in some special utils class. 

You can open a PR if you find it convenient :)
