### ISSUE TITLE
mount sopport

### ISSUE THREAD

**Issue by renxue** [SerCeMan/jnr-fuse#21]
Hi @SerCeMan I would like to put A machine on the /tmp directory mounted on the B machine /tmp under what should I do? Looked at your example, did not find the way I needed

**Comment by SerCeMan** [comment]
Hi, @renxue!

As far as I understand, you to have a shared directory between a few different machines. If so, you probably misunderstood what FUSE is. What you are asking can be implemented via fuse, but it's not what FUSE does. 

FUSE is just an interface that allows you to write a custom file system, you can find more about it here, https://en.wikipedia.org/wiki/Filesystem_in_Userspace .

**Comment by renxue** [comment]
This file: https://github.com/terencehonles/fusepy/blob/master/examples/loopback.py
I can execute the command "./python loopback.py A@/tmp   /tmp" to achieve what I said  put A machine on the /tmp directory mounted on the B machine /tmp under

**Comment by SerCeMan** [comment]
Apparently, this `loopback.py` is just an example of using FUSE. 
You can implement it using `jnr-fuse`, but it has nothing to do with the implementation of the FUSE API itself.

**Comment by renxue** [comment]
@SerCeMan Ok,  thank you very much for your answer.
