### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by pviotti** [SerCeMan/jnr-fuse#22]
Hi! I noticed that when I mount a file system it blurts out loads of logs on the command line like the following 

```
FUSE library version: 2.9.7
nullpath_ok: 0
nopath: 0
utime_omit_ok: 0
unique: 1, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
INIT: 7.26
flags=0x001ffffb
max_readahead=0x00020000
   INIT: 7.19
   flags=0x00000011
   max_readahead=0x00020000
   max_write=0x00020000
   max_background=0
   congestion_threshold=0
   unique: 1, success, outsize: 40
unique: 2, opcode: ACCESS (34), nodeid: 1, insize: 48, pid: 2340
   unique: 2, error: -38 (Function not implemented), outsize: 16
unique: 3, opcode: LOOKUP (1), nodeid: 1, insize: 47, pid: 2340
LOOKUP /.Trash
getattr /.Trash
   unique: 3, error: -2 (No such file or directory), outsize: 16
```
etc

Is this something that can be stopped programmatically with jnr-fuse or it depends on the low level FUSE implementation? 
(I'm using FUSE library 2.9.7, with Linux 4.11, on Arch Linux)

**Comment by SerCeMan** [comment]
Hi, @pviotti!

This might have happened because you passed `true` as a debug parameter when you mounted the FS. See https://github.com/SerCeMan/jnr-fuse/blob/master/src/main/java/ru/serce/jnrfuse/AbstractFuseFS.java#L226 for the reference.

**Comment by pviotti** [comment]
right, that's it, thank you! 👍
