### ISSUE TITLE
jnr-fuse and mutithreading?

### ISSUE THREAD

**Issue by omllobet** [SerCeMan/jnr-fuse#24]
Hi SerCeman,

We see that when we open a new file operation in a mounted directory like copying two files, the amount of bandwidth is divided between the two operations. My understanding is that it is because of the jnr-fuse and that the libfuse library supports multithreading. 

So is it possible to implement multithreading using jnr-fuse? Are there any limitations in jnr preventing that?

Thanks for any comments you make about the topic.

**Comment by SerCeMan** [comment]
Hi, @omllobet!

> So is it possible to implement multithreading using jnr-fuse? Are there any limitations in jnr preventing that?

Yes, it is possible. No, there are no limitations. jnr-fuse is a direct wrapper around fuse that directly calls fuse methods. That also implies that your filesystem implementation has to be thread-safe.

**Comment by omllobet** [comment]
Hi @SerCeMan 
Thanks for your answer. Do you have any example of a jnr-fuse filesystem using multithreading? If not, could you give me some recommendations or hints or a general idea to get me started? For example in my mind it is not clear how a fuse operation would be translated to it's own thread in java.

Thanks

**Comment by SerCeMan** [comment]
Hi, @omllobet!

You can think of it as "I don't know the thread that every single fuse method will be called on and I'll have to synchronise access to all shared state.". MemoryFS is an example of a thread-safe FS. Although it is not non-blocking, it uses `synchronized`.

**Comment by omllobet** [comment]
Hi @SerCeMan

Thanks for the information, it is a read only filesystem and not very complicated, so it should be doable. It is enough to have multithreading in the filesystem just by making it threadsafe? 

The calling part is where my mind has more problems. But if I understand correctly If I do 2 copy operations on the mounted filesystem each one will go to the same thread in java or not? something like cp program-> c library -> system call -> kernel -> (fuse ) -> libfuse ->java program. Do I have to create the threads in java to be able to manage various call (like in a rest program where there are some threads waiting for incoming connections) or a thread is created by libfuse for each operation?

Thanks again!

**Comment by SerCeMan** [comment]
> Do I have to create the threads in java to be able to manage various call

You don't have to create threads manually. Given that Java thread is a wrapper around a native thread, you'll be operating on a thread created by `fuse`. You can also read a discussion around a similar question: https://sourceforge.net/p/fuse/mailman/fuse-devel/thread/45D1DEC0.2090504@nortel.com/ for references.

**Comment by omllobet** [comment]
Great, thanks for the information.
