### ISSUE TITLE
Multiple new folder are created when using "New folder UI"?

### ISSUE THREAD

**Issue by ust3000** [SerCeMan/jnr-fuse#26]
Hello guys, 

I have tried to create new folder through windows UI 
![image](https://user-images.githubusercontent.com/7607968/30211264-3007001c-9498-11e7-9ea4-2f15f3ac4220.png)
 from [MemoryFS.java](https://github.com/SerCeMan/jnr-fuse/blob/master/src/main/java/ru/serce/jnrfuse/examples/MemoryFS.java), however i have got  
![image](https://user-images.githubusercontent.com/7607968/30211269-36e1a25c-9498-11e7-8007-2e2e938e6485.png)

And here logs : 
[jnr-fuse-new-folder.txt](https://github.com/SerCeMan/jnr-fuse/files/1287804/jnr-fuse-new-folder.txt)

Cloud you please figure out the issue and let us how to fix it ?

Best regards,
Mustapha.

**Comment by SerCeMan** [comment]
Hi, @ust3000!

The file explorer behaves in that way due to the `winfsp` requirement of setting permissions. I updated the `MemoryFS` example on `master`, see https://github.com/SerCeMan/jnr-fuse/commit/da4b7d41cd053f4a3f5c3809befd9d6dc95f4504

**Comment by ust3000** [comment]
@SerCeMan Thanks a lot. Now it works fine.
