### ISSUE TITLE
Extra error codes support for extended attributes

### ISSUE THREAD

**Issue by stanimirivanovde** [SerCeMan/jnr-fuse#29]
Looking at the man page on Mac OS X for getxattr() it lists the following errors as available, but those are not present in the ErrorCodes class:

     [ENOATTR]          The extended attribute does not exist.

     [ENOTSUP]          The file system does not support extended attributes or has the feature disabled.

     [EACCES]           Search permission is denied for a component of path or the attribute is not allowed to be read (e.g. an ACL prohibits reading the attributes of this file).
     
If the first one is not present, I can't tell the file system that the attribute name doesn't exist and it needs to be created.

**Comment by SerCeMan** [comment]
Hi, @stanimirivanovde!

Error codes are only numbers, so if I understand correctly, there is nothing that stops you from checking them now. 

As always, contributions are welcome! You can extend the `ru.serce.jnrfuse.ErrorCodes` by including these codes to make `jnr-fuse` better!

**Comment by stanimirivanovde** [comment]
Hi @SerCeMan, I'll look into it. It's a simple change.

**Comment by SerCeMan** [comment]
@philrykoff Thanks for that!
