### ISSUE TITLE
Unable to create multiple filesystems in Winfsp

### ISSUE THREAD

**Issue by WalkerKnapp** [SerCeMan/jnr-fuse#45]
After creating a filesystem and closing it with AbstractFuseFS#unmount(), any new filesystems created (with either the same path as the old filesystem or a new path) will fail with the error:
`Exception in thread "main" ru.serce.jnrfuse.FuseException: Unable to mount FS
	at ru.serce.jnrfuse.AbstractFuseFS.mount(AbstractFuseFS.java:286)
	at ru.serce.jnrfuse.Mountable.mount(Mountable.java:20)
	at com.walkerknapp.FuseTesting.UnmountTest.main(UnmountTest.java:29)
Caused by: ru.serce.jnrfuse.FuseException: Unable to mount FS, return code = 1
	at ru.serce.jnrfuse.AbstractFuseFS.mount(AbstractFuseFS.java:282)
	... 2 more`

I am unable to replicate this on any linux platforms, so I can only assume it is an issue with Winfsp and jnr-fuse.
This may be an issue with Winfsp itself, but I don't have the means to test it.

Can anyone replicate this? Are there any issues with what I'm trying to do? Thanks!

**Comment by WalkerKnapp** [comment]
Known issue of Winfsp

**Comment by msevcenko** [comment]
Yes, same behavior for me.

I use an ugly workaround - I launch my app through Launch4J wrapper, configured as "restart on crash". So when I want to unmount the filesystem, I simly do System.exit(1), which causes the app to restart in a fresh JVM process, able to do a new mount.
