### ISSUE TITLE
How can I enable buffer operations?

### ISSUE THREAD

**Issue by WalkerKnapp** [SerCeMan/jnr-fuse#46]
The Javadoc for FuseFS#write_buf() references `ru.serce.jnrfuse.AbstractFuseFS#isBufOperationsImplemented()` for enabling, but it appears to not exist. Any help with this would be appreciated. Thank you!

**Comment by SerCeMan** [comment]
Hi, @WalkerKnapp!

As far as I can see, this comment is obsolete, it doesn't mean anything now and should be deleted, so please disregard the comment. Also, feel free to open a PR to delete these comments.
