### ISSUE TITLE
JVM crash in utimens

### ISSUE THREAD

**Issue by chiastic-security** [SerCeMan/jnr-fuse#5]
I get a JVM crash when I try to access the second TimeSpec parameter (timespec[1]) inside a utimens() call. It is difficult to debug, because the debugger also crashes in its attempt to call toString() to display the contents of the variable.

It appears to be a problem inside the getNativeLong() call. It doesn't happen with timespec[0].

I wonder whether it's something to do with one of the special parameters UTIME_OMIT and UTIME_NOW being passed? It's unclear to me how these would be handled. See this page:

http://man7.org/linux/man-pages/man2/utimensat.2.html

In any case, I've attached the log file that the JVM produced.
[hs_err_pid6634.txt](https://github.com/SerCeMan/jnr-fuse/files/55833/hs_err_pid6634.txt)

**Comment by SerCeMan** [comment]
Hello!

I will look into it. Could you attach the exact Java-sample, which causes crash?

**Comment by chiastic-security** [comment]
Thanks! I can try to produce a minimal example that reproduces it.

**Comment by chiastic-security** [comment]
Attached is a minor modification of MemoryFS, which: adds a utimens() method; adds something to the getattr() call to return a non-zero modification time; adds a main method that mounts the filesystem, creates a file, and tries to copy it preserving timestamps.

I get a JVM crash with Oracle JDK 1.8.0_65.

[jvm-crash.zip](https://github.com/SerCeMan/jnr-fuse/files/55940/jvm-crash.zip)

**Comment by SerCeMan** [comment]
I found problem, it was my fault in dealing with jnr API, please try new '0.3' version, which i just deployed.

Thank you for contribution!

**Comment by chiastic-security** [comment]
Nice nice nice! Working fine now! Thank you.

Only issue I have remaining, and I don't know if it's related to this, is that the timestamp I receive from Files.getLastModifiedTime() always has a zero nanosecond part, so I can't get sub-second timestamp precision.

**Comment by SerCeMan** [comment]
I'm not sure the problem in threre, but if you submit issue with non-working code i will try to look into it.
