### ISSUE TITLE
FuseFileInfo : Padding objects

### ISSUE THREAD

**Issue by supermerill** [SerCeMan/jnr-fuse#53]
Hi

In open(), the FuseFileInfo contains some data in some Padding object.
The Padding class in protected so i can't do anything with it without reflection, it's intended?

Also, how to use these objects?

Thanks.
ps: i'm using your project for my distributed filesystem (https://github.com/supermerill/DistributedFs)

**Comment by SerCeMan** [comment]
Hi, yes, it's intended. Padding is only needed for proper alignment, and it shouldn't be used.
