### ISSUE TITLE
Update jnr-ffi to avoid illegal reflective access warning

### ISSUE THREAD

**Issue by overheadhunter** [SerCeMan/jnr-fuse#54]
Since jnr-ffi version 2.1.7 [this warning](https://github.com/jnr/jnr-ffi/issues/105) is fixed. ~~I verified compatibility by managing jnr-ffi to 2.1.8.~~ Therefore I'd suggest to update the dependency.

Update: `int readdir(String path, Pointer buf, FuseFillDir filter, @off_t long offset, FuseFileInfo fi)` doesn't get called any longer, when I update jnr-ffi to 2.1.8 (but it does work with 2.1.7). So apparently you can not just bump the version without adjusting the code.

**Comment by SerCeMan** [comment]
Hi, @overheadhunter! Thank you for reporting this! The issue was fixed in #59.
