### ISSUE TITLE
Calls open method on Windows during searching for a file and viewing a file property

### ISSUE THREAD

**Issue by arvgord** [SerCeMan/jnr-fuse#80]
Hi, @SerCeMan !

Thanks for the useful FUSE library!
I've implemented the [FUSE plugin](https://github.com/GoogleCloudPlatform/healthcare-api-dicom-fuse) for the Google Cloud Healthcare DICOM API. It works perfect on Linux but on Windows, I got an issue.
In the open method, I implemented a retrieving DICOM file from the server and cache it in the user's local storage on disk. When I open a file, I cache it and get file size from the server. I found that on Windows calls ***open*** method during searching for a file and viewing a file property(in jnr-fuse examples, it works similarly). This greatly reduces performance because I got unnecessary caching while searching for files. But in Linux open method calls only when I open a file. Could you help me with this issue?

**Comment by SerCeMan** [comment]
Hey, @arvgord! 

Nice work on the plugin! I think the behaviour might be related to the underlying behaviour of [winfsp](https://github.com/billziss-gh/winfsp). Could you duplicate your question there?

**Comment by arvgord** [comment]
I close this issue. I think the same question in WinFps repo may help someone!=) 
https://github.com/billziss-gh/winfsp/issues/247
