### ISSUE TITLE
NIO FileSystem support

### ISSUE THREAD

**Issue by josephsmendoza** [SerCeMan/jnr-fuse#91]
I was trying to build a filesystem with [javafs](https://github.com/puniverse/javafs) which is a FUSE Java library that uses Java native FileSystem instead of exposing the FUSE API. I tried using this library because javafs doesn't work on windows, but the API here is too low level for my needs. Any chance of implementing `FileSystem` in this project? If it's not difficult, some pointers on how to get started on that myself would be appreciated as well. Or if it's easier, [adding windows support to javafs](https://github.com/puniverse/javafs/issues/15)

**Comment by SerCeMan** [comment]
Hey, @josephsmendoza! I believe it makes sense for jnr-fuse to stay a simple building block which provides java interface on top of fuse. 

> If it's not difficult, some pointers on how to get started on that myself would be appreciated as well.

I think you could try to copy the corresponding files form `jnr-fuse` into [paralleluniverse/fuse ](https://github.com/puniverse/javafs/tree/master/src/main/java/co/paralleluniverse/fuse), and try to see what's missing. The chances are, it won't be much.

**Comment by overheadhunter** [comment]
@josephsmendoza You might want to check out our [fuse-nio-adapter](https://github.com/cryptomator/fuse-nio-adapter), adapts jnr-fuse to Java NIO.

**Comment by josephsmendoza** [comment]
Closing this issue in response to [this message](https://github.com/SerCeMan/jnr-fuse/issues/91#issuecomment-598107425)
