### ISSUE TITLE
Update jnr-ffi dependency

### ISSUE THREAD

**Issue by tobihagemann** [SerCeMan/jnr-fuse#94]
In the latest version of jffi, they fixed an important issue on macOS: https://github.com/jnr/jffi/issues/74

Our project is dependent on jnr-fuse and I wanted to ask if it's possible to update the jnr-ffi dependency to 2.1.12. Reading upon #61 and #72 it looks like that it's not a trivial version bump, is this still the case?

**Comment by SerCeMan** [comment]
Hi, @tobihagemann! 

https://github.com/jnr/jnr-ffi/pull/169 was resolved, so I believe it should be possible to bump jnr to the latest version if we combine it together with https://github.com/SerCeMan/jnr-fuse/pull/61.

**Comment by tobihagemann** [comment]
Unfortunately, we hit a roadblock now while trying to release an update of our project. We are unable to notarize the macOS app because of the aforementioned issue. Are there any blockers for merging #61?

**Comment by tobihagemann** [comment]
Looking good, thank you for the 0.5.4 update! Quick tests show that nothing broke and the notarization was also successful. 👍
