### ISSUE TITLE
jcenter URL is now https

### ISSUE THREAD

**Issue by canonicalchris** [SerCeMan/jnr-fuse#95]
Hi, Since January 2020, the bintray specification needs an HTTPS URL, not an HTTP URL, as your Maven example specifies.
`    <repositories>
        <repository>
            <id>central</id>
            <name>bintray</name>
            <url>https://jcenter.bintray.com</url>
        </repository>
    </repositories>
`
Hope that helps :)

**Comment by SerCeMan** [comment]
Hey, @canonicalchris! Thanks. I can fix it, or do you want to raise a PR?

**Comment by canonicalchris** [comment]
PR is pull-request?

**Comment by SerCeMan** [comment]
Yep, a pull request :)
